version: '3'
services:
  db:
    image: postgres:15.3-alpine3.18
    environment:
      - POSTGRES_DB=db_challenge
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"

  db_test:
    image: postgres:15.3-alpine3.18
    environment:
      - POSTGRES_DB=db_challenge_test
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5433:5432"

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/luiza-labs-challenge
    ports:
      - "3000:3000"
    depends_on:
      - db
      - db_test

